# Generated by Django 3.2.7 on 2021-09-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210925_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.part'),
        ),
    ]
