# Generated by Django 3.2.7 on 2021-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210928_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
